import Head from "next/head";
import Image from "next/image";
import { getNumberOfPage, getPostByPage } from "@/lib/notionAPI";
import SinglePost from "@/components/SinglePost";
import Pagination from "@/components/Pagination";

export const getStaticPaths = async () => {
  const numberOfPage = await getNumberOfPage();
  let params = [];
  for (let index = 1; index < numberOfPage; index++) {
    params.push({ params: { page: index.toString() } });
  }
  return {
    paths: params,
    fallback: "blocking", // can also be true or 'blocking'
  };
};
export const getStaticProps = async (context) => {
  const currentPage = context.params?.page;
  const postByPage = await getPostByPage(currentPage);
  const numberOfPage = await getNumberOfPage();

  return {
    props: {
      postByPage,
      numberOfPage,
    },
    revalidate: 60,
  };
};

export default function blogPageList(props) {
  return (
    <>
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-16 m-auto">
        <h2 className="text-lg text-center mb-16">Notion Blog</h2>
        <ul className="flex flex-wrap gap-7">
          {props.postByPage.map((post, index) => (
            <li key={index} className="bg-white flex-1 w-1/3  shadow-md">
              <SinglePost
                title={post.title}
                description={post.description}
                date={post.date}
                slug={post.slug}
                tags={post.tags}
              />
            </li>
          ))}
        </ul>
        <Pagination numberOfPage={props.numberOfPage} tag={""} />
      </main>
    </>
  );
}
