import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getAllPosts, getAllTags } from "@/lib/notionAPI";
import SinglePost from "@/components/SinglePost";
import Link from "next/link";
import Tag from "@/components/Tag";
export const getStaticProps = async () => {
  const allPosts = await getAllPosts();
  const allTags = await getAllTags();
  return {
    props: {
      allPosts,
      allTags,
    },
    revalidate: 60,
  };
};

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-16 m-auto">
        <h2 className="text-lg text-center mb-16">Notion Blog</h2>
        <ul className="flex flex-wrap gap-7">
          {props.allPosts.map((post, index) => (
            <li key={index} className="bg-white w-1/3  shadow-md">
              <SinglePost
                title={post.title}
                description={post.description}
                date={post.date}
                slug={post.slug}
                tags={post.tags}
              />
            </li>
          ))}
        </ul>
        <Link href={"/post/page/1"}>もっと見る</Link>
        <Tag allTags={props.allTags}></Tag>
      </main>
    </>
  );
}
